name: eco_clicker
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  audioplayers: ^5.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  hydrated_bloc: ^9.1.4
  localstorage: ^4.0.1+4
  marquee: ^2.2.3
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/earth1.png
    - assets/home.png
    - assets/shop.png
    - assets/stats.png
    - assets/settings.png
    - assets/energy_counter.png
    - assets/pollution_counter.png
    - assets/stars_bg.png
    - assets/Splash_Mac.png
    - assets/Splash_Iphone.png
    - assets/startGame.mp3